backend:
  name: github
  repo: mohsenfaraj/portfolio
  branch: main
  site_domain: https://mohsenfaraj.ir
  base_url: https://mohsenfaraj.ir
  auth_endpoint: /api/auth
media_folder: public/images
public_folder: /images
collections:
  - name: 'settings'
    label: 'Base Configuration'
    files:
      - file: 'data/base.yml'
        name: 'base'
        label: 'Site Settings'
        fields:
          - { label: 'Full Name', name: 'fullname', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'Titles'
            name: 'titles'
            widget: 'list'
          - { label: 'Base URL', name: 'BASEURL', widget: 'string' }
          - { label: 'Contact API URL', name: 'contactAPI', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Telegram', name: 'telegram', widget: 'string' }
          - { label: 'CV Link', name: 'CVLink', widget: 'string' }
      - file: 'data/nav.yml'
        name: links
        label: 'Navbar Links'
        fields:
          - label: Links
            widget: 'list'
            name: 'nav'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
      - file: 'data/socials.yml'
        name: socials
        label: social
        fields:
          - name: socials
            widget: 'list'
            label: Social link
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
              - { label: 'Icon', name: 'icon', widget: 'string' }
      - file: 'data/about.yml'
        name: 'cards'
        label: 'About'
        fields:
          - widget: list
            name: 'cards'
            label: 'About Card'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Body', name: 'body', widget: 'text' }
              - { label: 'Icon', name: 'icon', widget: 'string' }
      - file: 'data/skills.yml'
        name: skills
        label: Skills
        fields:
          - name: skills
            widget: 'list'
            label: Skill
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - {
                  label: 'Percentage',
                  name: 'percentage',
                  widget: 'number',
                  min: 0,
                  max: 100,
                }
              - { label: 'Icon', name: 'icon', widget: 'string' }
      - file: 'data/timeline.yml'
        name: timeline
        label: Events
        fields:
          - name: events
            widget: 'list'
            label: Event
            fields:
              - { label: 'Date', name: 'date', widget: 'text' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Body', name: 'body', widget: 'text' }
  - name: 'projcats'
    label: 'Projects'
    files:
      - file: 'data/categories.yml'
        name: categories
        label: Categories
        fields:
          - label: 'Categories'
            widget: 'list'
            name: categories
      - file: 'data/projects.yml'
        name: 'projects'
        label: 'Projects'
        fields:
          - label: 'Projects'
            widget: 'list'
            name: projects
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Short Description', name: 'short', widget: 'text' }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: 'image',
                  required: false,
                }
              - { label: 'Link', name: 'link', widget: 'string' }
              - label: 'Tags'
                name: 'tags'
                widget: 'relation'
                collection: 'projcats'
                value_field: 'categories.categories'
                search_fields: ['categories.categories']
                multiple: true
                required: false
