backend:
  name: github
  repo: mohsenfaraj/portfolio
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://mohsenfaraj.ir
  base_url: https://mohsenfaraj.ir
  auth_endpoint: /api/auth
media_folder: public/images
public_folder: /images
collections:
  - name: 'about'
    label: 'About'
    files:
      - file: 'data/about.yml'
        fields:
          - widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Body', name: 'body', widget: 'text' }
              - { label: 'Icon', name: 'icon', widget: 'string' }

  # Base configuration
  - name: 'base'
    label: 'Base Configuration'
    files:
      - file: 'data/base.yml'
        label: 'Site Settings'
        fields:
          - { label: 'Full Name', name: 'fullname', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'Titles'
            name: 'titles'
            widget: 'list'
          - { label: 'Base URL', name: 'BASEURL', widget: 'string' }
          - { label: 'Contact API URL', name: 'contactAPI', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Telegram', name: 'telegram', widget: 'string' }
          - { label: 'CV Link', name: 'CVLink', widget: 'string' }

  # Navigation
  - name: 'nav'
    label: 'Navigation'
    files:
      - file: 'data/nav.yml'
        fields:
          - label: Links
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }

  # Projects
  - name: 'projects'
    label: 'Projects'
    files:
      - file: 'data/projects.yml'
        label: 'Projects'
        fields:
          - label: 'Projects'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Short Description', name: 'short', widget: 'text' }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: 'image',
                  required: false,
                }
              - { label: 'Link', name: 'link', widget: 'string' }
              - label: 'Tags'
                name: 'tags'
                widget: 'relation'
                collection: 'categories'
                value_field: 'categories.*'
                search_fields: ['categories.*']
                multiple: true

  - name: 'categories'
    label: 'Categories'
    widget: 'list'

  # Skills
  - name: 'skills'
    label: 'Skills'
    files:
      - file: 'data/skills.yml'
        fields:
          - name: skill
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - {
                  label: 'Percentage',
                  name: 'percentage',
                  widget: 'number',
                  min: 0,
                  max: 100,
                }
              - { label: 'Icon', name: 'icon', widget: 'string' }

  # Social Links
  - name: 'socials'
    label: 'Social Links'
    files:
      - file: 'data/socials.yml'
        fields:
          - name: social link
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
              - { label: 'Icon', name: 'icon', widget: 'string' }
